/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\viteTest\\blog\\my-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-4ac6569c",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ac6569c").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-b5425aa6",
    path: "/handbook/Byte/object.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b5425aa6").then(next)
    },
  },
  {
    name: "v-29fe9c7f",
    path: "/handbook/Byte/array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-29fe9c7f").then(next)
    },
  },
  {
    name: "v-78061042",
    path: "/handbook/Byte/pubuliu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78061042").then(next)
    },
  },
  {
    name: "v-1fa58acf",
    path: "/handbook/Byte/sanleibuju.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1fa58acf").then(next)
    },
  },
  {
    name: "v-7af95c37",
    path: "/handbook/ES6/async-await.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7af95c37").then(next)
    },
  },
  {
    name: "v-6a375eea",
    path: "/handbook/ES6/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a375eea").then(next)
    },
  },
  {
    name: "v-0fdacb8b",
    path: "/handbook/ES6/for-in-of.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0fdacb8b").then(next)
    },
  },
  {
    name: "v-3072887f",
    path: "/handbook/JavaScript/jicheng.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3072887f").then(next)
    },
  },
  {
    name: "v-0801ecf5",
    path: "/handbook/JavaScript/ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0801ecf5").then(next)
    },
  },
  {
    name: "v-69d6624a",
    path: "/handbook/JavaScript/kaobei.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69d6624a").then(next)
    },
  },
  {
    name: "v-0cdc6c9f",
    path: "/handbook/JavaScript/leixingzhuanghuan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0cdc6c9f").then(next)
    },
  },
  {
    name: "v-6a1ada79",
    path: "/handbook/JavaScript/this.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6a1ada79").then(next)
    },
  },
  {
    name: "v-51d5f082",
    path: "/handbook/JavaScript/xianshibangding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51d5f082").then(next)
    },
  },
  {
    name: "v-ff3b63e2",
    path: "/handbook/JavaScript/yuanxing.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ff3b63e2").then(next)
    },
  },
  {
    name: "v-390d00c2",
    path: "/handbook/JavaScript/zuoyongyu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-390d00c2").then(next)
    },
  },
  {
    name: "v-c701914c",
    path: "/handbook/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c701914c").then(next)
    },
  },
  {
    path: "/handbook/Vue/index.html",
    redirect: "/handbook/Vue/"
  },
  {
    name: "v-07be16ff",
    path: "/handbook/Node/kuayu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-07be16ff").then(next)
    },
  },
  {
    name: "v-5b89e3f9",
    path: "/handbook/Vue/router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5b89e3f9").then(next)
    },
  },
  {
    name: "v-373c09df",
    path: "/handbook/andition/bianpinghua.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-373c09df").then(next)
    },
  },
  {
    name: "v-4d868802",
    path: "/handbook/andition/fabudingyue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d868802").then(next)
    },
  },
  {
    name: "v-59e905bf",
    path: "/handbook/andition/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-59e905bf").then(next)
    },
  },
  {
    name: "v-c4f33a16",
    path: "/views/About/author.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c4f33a16").then(next)
    },
  },
  {
    name: "v-9e23ecc2",
    path: "/views/Resume/resume.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9e23ecc2").then(next)
    },
  },
  {
    name: "v-b08060b6",
    path: "/views/other/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b08060b6").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-2393e274",
    path: "/tag/Object/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2393e274").then(next)
    },
    meta: {"pid":"tags","id":"Object"}
  },
  {
    path: "/tag/Object/index.html",
    redirect: "/tag/Object/"
  },
  {
    name: "v-7d137840",
    path: "/tag/Array/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7d137840").then(next)
    },
    meta: {"pid":"tags","id":"Array"}
  },
  {
    path: "/tag/Array/index.html",
    redirect: "/tag/Array/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-3257dcde",
    path: "/tag/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3257dcde").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tag/ES6/index.html",
    redirect: "/tag/ES6/"
  },
  {
    name: "v-c784ecce",
    path: "/tag/继承/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-c784ecce").then(next)
    },
    meta: {"pid":"tags","id":"继承"}
  },
  {
    path: "/tag/继承/index.html",
    redirect: "/tag/继承/"
  },
  {
    name: "v-5f66a358",
    path: "/tag/javaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5f66a358").then(next)
    },
    meta: {"pid":"tags","id":"javaScript"}
  },
  {
    path: "/tag/javaScript/index.html",
    redirect: "/tag/javaScript/"
  },
  {
    name: "v-d74bd976",
    path: "/tag/深浅拷贝/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d74bd976").then(next)
    },
    meta: {"pid":"tags","id":"深浅拷贝"}
  },
  {
    path: "/tag/深浅拷贝/index.html",
    redirect: "/tag/深浅拷贝/"
  },
  {
    name: "v-0b8093b7",
    path: "/tag/类型转换/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0b8093b7").then(next)
    },
    meta: {"pid":"tags","id":"类型转换"}
  },
  {
    path: "/tag/类型转换/index.html",
    redirect: "/tag/类型转换/"
  },
  {
    name: "v-0df5b1b6",
    path: "/tag/八股文/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0df5b1b6").then(next)
    },
    meta: {"pid":"tags","id":"八股文"}
  },
  {
    path: "/tag/八股文/index.html",
    redirect: "/tag/八股文/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-67cf2c0a",
    path: "/tag/跨域/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-67cf2c0a").then(next)
    },
    meta: {"pid":"tags","id":"跨域"}
  },
  {
    path: "/tag/跨域/index.html",
    redirect: "/tag/跨域/"
  },
  {
    name: "v-4081041c",
    path: "/tag/router/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4081041c").then(next)
    },
    meta: {"pid":"tags","id":"router"}
  },
  {
    path: "/tag/router/index.html",
    redirect: "/tag/router/"
  },
  {
    name: "v-2892531a",
    path: "/tag/扁平化/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2892531a").then(next)
    },
    meta: {"pid":"tags","id":"扁平化"}
  },
  {
    path: "/tag/扁平化/index.html",
    redirect: "/tag/扁平化/"
  },
  {
    name: "v-1d861698",
    path: "/tag/发布订阅/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1d861698").then(next)
    },
    meta: {"pid":"tags","id":"发布订阅"}
  },
  {
    path: "/tag/发布订阅/index.html",
    redirect: "/tag/发布订阅/"
  },
  {
    name: "v-19493022",
    path: "/tag/面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-19493022").then(next)
    },
    meta: {"pid":"tags","id":"面试题"}
  },
  {
    path: "/tag/面试题/index.html",
    redirect: "/tag/面试题/"
  },
  {
    name: "v-60d1e5a9",
    path: "/categories/Byte/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-60d1e5a9").then(next)
    },
    meta: {"pid":"categories","id":"Byte"}
  },
  {
    path: "/categories/Byte/index.html",
    redirect: "/categories/Byte/"
  },
  {
    name: "v-7eff4a05",
    path: "/categories/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7eff4a05").then(next)
    },
    meta: {"pid":"categories","id":"ES6"}
  },
  {
    path: "/categories/ES6/index.html",
    redirect: "/categories/ES6/"
  },
  {
    name: "v-081e6844",
    path: "/categories/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-081e6844").then(next)
    },
    meta: {"pid":"categories","id":"JavaScript"}
  },
  {
    path: "/categories/JavaScript/index.html",
    redirect: "/categories/JavaScript/"
  },
  {
    name: "v-7f0789a7",
    path: "/categories/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f0789a7").then(next)
    },
    meta: {"pid":"categories","id":"Vue"}
  },
  {
    path: "/categories/Vue/index.html",
    redirect: "/categories/Vue/"
  },
  {
    name: "v-617637ef",
    path: "/categories/Node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-617637ef").then(next)
    },
    meta: {"pid":"categories","id":"Node"}
  },
  {
    path: "/categories/Node/index.html",
    redirect: "/categories/Node/"
  },
  {
    name: "v-6eaeda0b",
    path: "/categories/andition/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6eaeda0b").then(next)
    },
    meta: {"pid":"categories","id":"andition"}
  },
  {
    path: "/categories/andition/index.html",
    redirect: "/categories/andition/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]