/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\86131\\Desktop\\my-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-0059c412",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0059c412").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-e5e0fe6e",
    path: "/handbook/Byte/array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e5e0fe6e").then(next)
    },
  },
  {
    name: "v-f0706712",
    path: "/handbook/Byte/object.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f0706712").then(next)
    },
  },
  {
    name: "v-9fe2b1ae",
    path: "/handbook/Byte/pubuliu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9fe2b1ae").then(next)
    },
  },
  {
    name: "v-aff5cace",
    path: "/handbook/Byte/sanleibuju.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-aff5cace").then(next)
    },
  },
  {
    name: "v-0358ec01",
    path: "/handbook/ES6/async-await.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0358ec01").then(next)
    },
  },
  {
    name: "v-df3d0682",
    path: "/handbook/JavaScript/ajax.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-df3d0682").then(next)
    },
  },
  {
    name: "v-0e5598c9",
    path: "/handbook/JavaScript/jicheng.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e5598c9").then(next)
    },
  },
  {
    name: "v-3e3dd055",
    path: "/handbook/ES6/for-in-of.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e3dd055").then(next)
    },
  },
  {
    name: "v-a5656b56",
    path: "/handbook/ES6/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a5656b56").then(next)
    },
  },
  {
    name: "v-13992cb6",
    path: "/handbook/JavaScript/kaobei.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13992cb6").then(next)
    },
  },
  {
    name: "v-1b0b2b7a",
    path: "/handbook/JavaScript/this.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1b0b2b7a").then(next)
    },
  },
  {
    name: "v-6acefb49",
    path: "/handbook/Node/kuayu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6acefb49").then(next)
    },
  },
  {
    name: "v-71c273d9",
    path: "/handbook/JavaScript/yuanxing.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71c273d9").then(next)
    },
  },
  {
    name: "v-4ece73e9",
    path: "/handbook/JavaScript/leixingzhuanghuan.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4ece73e9").then(next)
    },
  },
  {
    name: "v-05314a2e",
    path: "/handbook/JavaScript/zuoyongyu.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05314a2e").then(next)
    },
  },
  {
    name: "v-b6468ab8",
    path: "/handbook/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b6468ab8").then(next)
    },
  },
  {
    path: "/handbook/Vue/index.html",
    redirect: "/handbook/Vue/"
  },
  {
    name: "v-82ca6f7a",
    path: "/handbook/Vue/router.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-82ca6f7a").then(next)
    },
  },
  {
    name: "v-7df24409",
    path: "/handbook/JavaScript/xianshibangding.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7df24409").then(next)
    },
  },
  {
    name: "v-19aad16e",
    path: "/handbook/andition/fabudingyue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19aad16e").then(next)
    },
  },
  {
    name: "v-5129e529",
    path: "/handbook/andition/bianpinghua.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5129e529").then(next)
    },
  },
  {
    name: "v-48a3cb09",
    path: "/handbook/andition/promise.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-48a3cb09").then(next)
    },
  },
  {
    name: "v-b1905c82",
    path: "/views/About/author.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b1905c82").then(next)
    },
  },
  {
    name: "v-389b2e22",
    path: "/views/other/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-389b2e22").then(next)
    },
  },
  {
    name: "v-13feede9",
    path: "/views/Resume/resume.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-13feede9").then(next)
    },
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-7d137840",
    path: "/tag/Array/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-7d137840").then(next)
    },
    meta: {"pid":"tags","id":"Array"}
  },
  {
    path: "/tag/Array/index.html",
    redirect: "/tag/Array/"
  },
  {
    name: "v-2393e274",
    path: "/tag/Object/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2393e274").then(next)
    },
    meta: {"pid":"tags","id":"Object"}
  },
  {
    path: "/tag/Object/index.html",
    redirect: "/tag/Object/"
  },
  {
    name: "v-3259a754",
    path: "/tag/CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3259a754").then(next)
    },
    meta: {"pid":"tags","id":"CSS"}
  },
  {
    path: "/tag/CSS/index.html",
    redirect: "/tag/CSS/"
  },
  {
    name: "v-3257dcde",
    path: "/tag/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-3257dcde").then(next)
    },
    meta: {"pid":"tags","id":"ES6"}
  },
  {
    path: "/tag/ES6/index.html",
    redirect: "/tag/ES6/"
  },
  {
    name: "v-5f66a358",
    path: "/tag/javaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-5f66a358").then(next)
    },
    meta: {"pid":"tags","id":"javaScript"}
  },
  {
    path: "/tag/javaScript/index.html",
    redirect: "/tag/javaScript/"
  },
  {
    name: "v-c784ecce",
    path: "/tag/继承/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-c784ecce").then(next)
    },
    meta: {"pid":"tags","id":"继承"}
  },
  {
    path: "/tag/继承/index.html",
    redirect: "/tag/继承/"
  },
  {
    name: "v-d74bd976",
    path: "/tag/深浅拷贝/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-d74bd976").then(next)
    },
    meta: {"pid":"tags","id":"深浅拷贝"}
  },
  {
    path: "/tag/深浅拷贝/index.html",
    redirect: "/tag/深浅拷贝/"
  },
  {
    name: "v-67cf2c0a",
    path: "/tag/跨域/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-67cf2c0a").then(next)
    },
    meta: {"pid":"tags","id":"跨域"}
  },
  {
    path: "/tag/跨域/index.html",
    redirect: "/tag/跨域/"
  },
  {
    name: "v-0df5b1b6",
    path: "/tag/八股文/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0df5b1b6").then(next)
    },
    meta: {"pid":"tags","id":"八股文"}
  },
  {
    path: "/tag/八股文/index.html",
    redirect: "/tag/八股文/"
  },
  {
    name: "v-0b8093b7",
    path: "/tag/类型转换/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0b8093b7").then(next)
    },
    meta: {"pid":"tags","id":"类型转换"}
  },
  {
    path: "/tag/类型转换/index.html",
    redirect: "/tag/类型转换/"
  },
  {
    name: "v-322a45da",
    path: "/tag/vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-322a45da").then(next)
    },
    meta: {"pid":"tags","id":"vue"}
  },
  {
    path: "/tag/vue/index.html",
    redirect: "/tag/vue/"
  },
  {
    name: "v-4081041c",
    path: "/tag/router/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-4081041c").then(next)
    },
    meta: {"pid":"tags","id":"router"}
  },
  {
    path: "/tag/router/index.html",
    redirect: "/tag/router/"
  },
  {
    name: "v-1d861698",
    path: "/tag/发布订阅/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-1d861698").then(next)
    },
    meta: {"pid":"tags","id":"发布订阅"}
  },
  {
    path: "/tag/发布订阅/index.html",
    redirect: "/tag/发布订阅/"
  },
  {
    name: "v-2892531a",
    path: "/tag/扁平化/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-2892531a").then(next)
    },
    meta: {"pid":"tags","id":"扁平化"}
  },
  {
    path: "/tag/扁平化/index.html",
    redirect: "/tag/扁平化/"
  },
  {
    name: "v-19493022",
    path: "/tag/面试题/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-19493022").then(next)
    },
    meta: {"pid":"tags","id":"面试题"}
  },
  {
    path: "/tag/面试题/index.html",
    redirect: "/tag/面试题/"
  },
  {
    name: "v-60d1e5a9",
    path: "/categories/Byte/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-60d1e5a9").then(next)
    },
    meta: {"pid":"categories","id":"Byte"}
  },
  {
    path: "/categories/Byte/index.html",
    redirect: "/categories/Byte/"
  },
  {
    name: "v-7eff4a05",
    path: "/categories/ES6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7eff4a05").then(next)
    },
    meta: {"pid":"categories","id":"ES6"}
  },
  {
    path: "/categories/ES6/index.html",
    redirect: "/categories/ES6/"
  },
  {
    name: "v-081e6844",
    path: "/categories/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-081e6844").then(next)
    },
    meta: {"pid":"categories","id":"JavaScript"}
  },
  {
    path: "/categories/JavaScript/index.html",
    redirect: "/categories/JavaScript/"
  },
  {
    name: "v-617637ef",
    path: "/categories/Node/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-617637ef").then(next)
    },
    meta: {"pid":"categories","id":"Node"}
  },
  {
    path: "/categories/Node/index.html",
    redirect: "/categories/Node/"
  },
  {
    name: "v-7f0789a7",
    path: "/categories/Vue/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-7f0789a7").then(next)
    },
    meta: {"pid":"categories","id":"Vue"}
  },
  {
    path: "/categories/Vue/index.html",
    redirect: "/categories/Vue/"
  },
  {
    name: "v-6eaeda0b",
    path: "/categories/andition/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-6eaeda0b").then(next)
    },
    meta: {"pid":"categories","id":"andition"}
  },
  {
    path: "/categories/andition/index.html",
    redirect: "/categories/andition/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]