/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "穷小白的博客",
  "description": "举杯邀明月，对影成三人~",
  "base": "/my-blog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/my-blog/headPortrait.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "穷小白的博客",
        "tagline": "举杯邀明月，对影成三人~"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-4ac6569c",
      "path": "/",
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "对象各种好用的API手写",
      "frontmatter": {
        "title": "对象各种好用的API手写",
        "date": "2022-12-07T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "Object"
        ],
        "categories": [
          "Byte"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Byte/object.html",
      "relativePath": "handbook/Byte/object.md",
      "key": "v-b5425aa6",
      "path": "/handbook/Byte/object.html",
      "headers": [
        {
          "level": 2,
          "title": "3. Object.fromEntries()",
          "slug": "_3-object-fromentries"
        },
        {
          "level": 2,
          "title": "4. Object.keys()",
          "slug": "_4-object-keys"
        },
        {
          "level": 2,
          "title": "5. Object.values()",
          "slug": "_5-object-values"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "高级CSS属性实现的瀑布流的三种方法",
      "frontmatter": {
        "title": "高级CSS属性实现的瀑布流的三种方法",
        "date": "2022-08-29T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "CSS"
        ],
        "categories": [
          "Byte"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Byte/pubuliu.html",
      "relativePath": "handbook/Byte/pubuliu.md",
      "key": "v-78061042",
      "path": "/handbook/Byte/pubuliu.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "多栏布局实现瀑布流",
          "slug": "多栏布局实现瀑布流"
        },
        {
          "level": 2,
          "title": "网格布局实现瀑布流",
          "slug": "网格布局实现瀑布流"
        },
        {
          "level": 2,
          "title": "弹性布局实现瀑布流",
          "slug": "弹性布局实现瀑布流"
        },
        {
          "level": 2,
          "title": "结语",
          "slug": "结语"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "数组各种好用API的手写",
      "frontmatter": {
        "title": "数组各种好用API的手写",
        "date": "2022-12-06T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "Array"
        ],
        "categories": [
          "Byte"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Byte/array.html",
      "relativePath": "handbook/Byte/array.md",
      "key": "v-29fe9c7f",
      "path": "/handbook/Byte/array.html",
      "headers": [
        {
          "level": 2,
          "title": "2.1 Array.every()",
          "slug": "_2-1-array-every"
        },
        {
          "level": 2,
          "title": "2.2 Array.some()",
          "slug": "_2-2-array-some"
        },
        {
          "level": 3,
          "title": "1.some()原理",
          "slug": "_1-some-原理"
        },
        {
          "level": 3,
          "title": "2.some()方法的手写实现",
          "slug": "_2-some-方法的手写实现"
        },
        {
          "level": 2,
          "title": "2.3 Array.map()",
          "slug": "_2-3-array-map"
        },
        {
          "level": 3,
          "title": "1.map()原理",
          "slug": "_1-map-原理"
        },
        {
          "level": 3,
          "title": "2.map()方法的手写实现",
          "slug": "_2-map-方法的手写实现"
        },
        {
          "level": 2,
          "title": "2.4 Array.reduce()",
          "slug": "_2-4-array-reduce"
        },
        {
          "level": 3,
          "title": "1.reduce()原理",
          "slug": "_1-reduce-原理"
        },
        {
          "level": 3,
          "title": "2.reduce()方法的手写实现",
          "slug": "_2-reduce-方法的手写实现"
        },
        {
          "level": 2,
          "title": "2.5 Array.filter()",
          "slug": "_2-5-array-filter"
        },
        {
          "level": 3,
          "title": "1.filter()原理",
          "slug": "_1-filter-原理"
        },
        {
          "level": 3,
          "title": "2.filter()方法的手写实现",
          "slug": "_2-filter-方法的手写实现"
        },
        {
          "level": 2,
          "title": "2.6 Array.forEach()",
          "slug": "_2-6-array-foreach"
        },
        {
          "level": 3,
          "title": "1.forEach()原理",
          "slug": "_1-foreach-原理"
        },
        {
          "level": 3,
          "title": "2.forEach()方法的手写实现",
          "slug": "_2-foreach-方法的手写实现"
        },
        {
          "level": 2,
          "title": "3.1 Array.find()",
          "slug": "_3-1-array-find"
        },
        {
          "level": 3,
          "title": "1.find()原理",
          "slug": "_1-find-原理"
        },
        {
          "level": 3,
          "title": "2.find()方法的手写实现",
          "slug": "_2-find-方法的手写实现"
        },
        {
          "level": 2,
          "title": "3.2 Array.findIndex()",
          "slug": "_3-2-array-findindex"
        },
        {
          "level": 3,
          "title": "1.findIndex()原理",
          "slug": "_1-findindex-原理"
        },
        {
          "level": 3,
          "title": "2.findIndex()方法的手写实现",
          "slug": "_2-findindex-方法的手写实现"
        },
        {
          "level": 2,
          "title": "4.1 Array.include()",
          "slug": "_4-1-array-include"
        },
        {
          "level": 3,
          "title": "1.includes()原理",
          "slug": "_1-includes-原理"
        },
        {
          "level": 3,
          "title": "2.includes()方法的手写实现",
          "slug": "_2-includes-方法的手写实现"
        },
        {
          "level": 2,
          "title": "4.2 Array.join()",
          "slug": "_4-2-array-join"
        },
        {
          "level": 3,
          "title": "1.join()原理",
          "slug": "_1-join-原理"
        },
        {
          "level": 3,
          "title": "2.join()方法的手写实现",
          "slug": "_2-join-方法的手写实现"
        },
        {
          "level": 2,
          "title": "4.3 Array.flat()",
          "slug": "_4-3-array-flat"
        },
        {
          "level": 3,
          "title": "1.flat()原理",
          "slug": "_1-flat-原理"
        },
        {
          "level": 3,
          "title": "2.flat()方法的手写实现",
          "slug": "_2-flat-方法的手写实现"
        },
        {
          "level": 2,
          "title": "4.4 Array.splice()",
          "slug": "_4-4-array-splice"
        },
        {
          "level": 3,
          "title": "1.splice()原理",
          "slug": "_1-splice-原理"
        },
        {
          "level": 3,
          "title": "2.splice()方法的手写实现",
          "slug": "_2-splice-方法的手写实现"
        },
        {
          "level": 2,
          "title": "4.5 Array.fill()",
          "slug": "_4-5-array-fill"
        },
        {
          "level": 3,
          "title": "1.fill()原理",
          "slug": "_1-fill-原理"
        },
        {
          "level": 3,
          "title": "2.fill()方法的手写实现",
          "slug": "_2-fill-方法的手写实现"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "ES6——promise对象",
      "frontmatter": {
        "title": "ES6——promise对象",
        "date": "2022-07-28T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "ES6"
        ],
        "categories": [
          "ES6"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/ES6/async-await.html",
      "relativePath": "handbook/ES6/async-await.md",
      "key": "v-7af95c37",
      "path": "/handbook/ES6/async-await.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "asnyc-await",
          "slug": "asnyc-await"
        },
        {
          "level": 3,
          "title": "asnyc",
          "slug": "asnyc"
        },
        {
          "level": 3,
          "title": "await",
          "slug": "await"
        },
        {
          "level": 2,
          "title": "结语",
          "slug": "结语"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "CSS经典三列布局—圣杯布局与双飞翼布局",
      "frontmatter": {
        "title": "CSS经典三列布局—圣杯布局与双飞翼布局",
        "date": "2022-07-10T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "CSS"
        ],
        "categories": [
          "Byte"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Byte/sanleibuju.html",
      "relativePath": "handbook/Byte/sanleibuju.md",
      "key": "v-1fa58acf",
      "path": "/handbook/Byte/sanleibuju.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "圣杯布局代码解析",
          "slug": "圣杯布局代码解析"
        },
        {
          "level": 2,
          "title": "HTML代码",
          "slug": "html代码"
        },
        {
          "level": 2,
          "title": "CSS代码",
          "slug": "css代码"
        },
        {
          "level": 2,
          "title": "双飞翼布局代码解析",
          "slug": "双飞翼布局代码解析"
        },
        {
          "level": 2,
          "title": "HTML代码",
          "slug": "html代码-2"
        },
        {
          "level": 2,
          "title": "CSS代码",
          "slug": "css代码-2"
        },
        {
          "level": 2,
          "title": "异同",
          "slug": "异同"
        },
        {
          "level": 2,
          "title": "小结",
          "slug": "小结"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "简洁明了的循环写法 for in-of",
      "frontmatter": {
        "title": "简洁明了的循环写法 for in-of",
        "date": "2022-07-31T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "ES6"
        ],
        "categories": [
          "ES6"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/ES6/for-in-of.html",
      "relativePath": "handbook/ES6/for-in-of.md",
      "key": "v-0fdacb8b",
      "path": "/handbook/ES6/for-in-of.html",
      "headers": [
        {
          "level": 2,
          "title": "Iterator（遍历器）",
          "slug": "iterator-遍历器"
        },
        {
          "level": 2,
          "title": "for in",
          "slug": "for-in"
        },
        {
          "level": 3,
          "title": "使用场景：",
          "slug": "使用场景"
        },
        {
          "level": 2,
          "title": "for of",
          "slug": "for-of"
        },
        {
          "level": 3,
          "title": "使用场景",
          "slug": "使用场景-2"
        },
        {
          "level": 2,
          "title": "区别",
          "slug": "区别"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "ES6——promise对象",
      "frontmatter": {
        "title": "ES6——promise对象",
        "date": "2022-07-20T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "ES6"
        ],
        "categories": [
          "ES6"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/ES6/promise.html",
      "relativePath": "handbook/ES6/promise.md",
      "key": "v-6a375eea",
      "path": "/handbook/ES6/promise.html",
      "headers": [
        {
          "level": 2,
          "title": "Promise的含义",
          "slug": "promise的含义"
        },
        {
          "level": 2,
          "title": "Promise的基本用法",
          "slug": "promise的基本用法"
        },
        {
          "level": 2,
          "title": "Promise的方法",
          "slug": "promise的方法"
        },
        {
          "level": 2,
          "title": "Promise的应用场景和不足之处",
          "slug": "promise的应用场景和不足之处"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "来手撸一个简化版Ajax",
      "frontmatter": {
        "title": "来手撸一个简化版Ajax",
        "date": "2022-09-25T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "javaScript"
        ],
        "categories": [
          "JavaScript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/JavaScript/ajax.html",
      "relativePath": "handbook/JavaScript/ajax.md",
      "key": "v-0801ecf5",
      "path": "/handbook/JavaScript/ajax.html",
      "headers": [
        {
          "level": 3,
          "title": "Ajax是什么",
          "slug": "ajax是什么"
        },
        {
          "level": 3,
          "title": "Ajax的作用",
          "slug": "ajax的作用"
        },
        {
          "level": 2,
          "title": "原生JS向后端请求方式",
          "slug": "原生js向后端请求方式"
        },
        {
          "level": 3,
          "title": "readyState的状态",
          "slug": "readystate的状态"
        },
        {
          "level": 3,
          "title": "http状态码",
          "slug": "http状态码"
        },
        {
          "level": 3,
          "title": "我们来一个实例",
          "slug": "我们来一个实例"
        },
        {
          "level": 2,
          "title": "直接使用封装好的Ajax方法",
          "slug": "直接使用封装好的ajax方法"
        },
        {
          "level": 2,
          "title": "手撸一个简化版Ajax",
          "slug": "手撸一个简化版ajax"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "JS语言的一座小山坡——‘this’",
      "frontmatter": {
        "title": "JS语言的一座小山坡——‘this’",
        "date": "2022-07-10T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "继承"
        ],
        "categories": [
          "JavaScript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/JavaScript/jicheng.html",
      "relativePath": "handbook/JavaScript/jicheng.md",
      "key": "v-3072887f",
      "path": "/handbook/JavaScript/jicheng.html",
      "headers": [
        {
          "level": 2,
          "title": "2. 原型链继承",
          "slug": "_2-原型链继承"
        },
        {
          "level": 2,
          "title": "3. 经典继承(伪造对象）",
          "slug": "_3-经典继承-伪造对象"
        },
        {
          "level": 2,
          "title": "4. 组合继承（伪经典继承）",
          "slug": "_4-组合继承-伪经典继承"
        },
        {
          "level": 2,
          "title": "5. 原型式继承",
          "slug": "_5-原型式继承"
        },
        {
          "level": 2,
          "title": "6. 寄生式继承",
          "slug": "_6-寄生式继承"
        },
        {
          "level": 2,
          "title": "7. 寄生组合式继承",
          "slug": "_7-寄生组合式继承"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "深or浅拷贝，带你从入门到精通",
      "frontmatter": {
        "title": "深or浅拷贝，带你从入门到精通",
        "date": "2022-12-24T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "深浅拷贝"
        ],
        "categories": [
          "JavaScript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/JavaScript/kaobei.html",
      "relativePath": "handbook/JavaScript/kaobei.md",
      "key": "v-69d6624a",
      "path": "/handbook/JavaScript/kaobei.html",
      "headers": [
        {
          "level": 2,
          "title": "浅拷贝",
          "slug": "浅拷贝"
        },
        {
          "level": 3,
          "title": "1、赋值",
          "slug": "_1、赋值"
        },
        {
          "level": 3,
          "title": "2. Object.assign()",
          "slug": "_2-object-assign"
        },
        {
          "level": 3,
          "title": "3. 解构",
          "slug": "_3-解构"
        },
        {
          "level": 2,
          "title": "深拷贝",
          "slug": "深拷贝"
        },
        {
          "level": 3,
          "title": "1. JSON.parse() 和 JSON.stringify()",
          "slug": "_1-json-parse-和-json-stringify"
        },
        {
          "level": 2,
          "title": "可深可浅方法",
          "slug": "可深可浅方法"
        },
        {
          "level": 2,
          "title": "浅拷贝",
          "slug": "浅拷贝-2"
        },
        {
          "level": 2,
          "title": "深拷贝",
          "slug": "深拷贝-2"
        },
        {
          "level": 2,
          "title": "1. 介绍",
          "slug": "_1-介绍"
        },
        {
          "level": 2,
          "title": "2.实现",
          "slug": "_2-实现"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "解析JS中的类型转换",
      "frontmatter": {
        "title": "解析JS中的类型转换",
        "date": "2022-08-29T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "类型转换"
        ],
        "categories": [
          "JavaScript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/JavaScript/leixingzhuanghuan.html",
      "relativePath": "handbook/JavaScript/leixingzhuanghuan.md",
      "key": "v-0cdc6c9f",
      "path": "/handbook/JavaScript/leixingzhuanghuan.html",
      "headers": [
        {
          "level": 2,
          "title": "原始类型转对象",
          "slug": "原始类型转对象"
        },
        {
          "level": 2,
          "title": "对象转原始类型",
          "slug": "对象转原始类型"
        },
        {
          "level": 2,
          "title": "隐式类型转换",
          "slug": "隐式类型转换"
        },
        {
          "level": 3,
          "title": "一元运算符",
          "slug": "一元运算符"
        },
        {
          "level": 3,
          "title": "二元操作符",
          "slug": "二元操作符"
        },
        {
          "level": 3,
          "title": "二元运算符",
          "slug": "二元运算符"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "JavaScript的6种常用继承方式",
      "frontmatter": {
        "title": "JavaScript的6种常用继承方式",
        "date": "2022-12-09T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "继承"
        ],
        "categories": [
          "JavaScript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/JavaScript/this.html",
      "relativePath": "handbook/JavaScript/this.md",
      "key": "v-6a1ada79",
      "path": "/handbook/JavaScript/this.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "this的绑定规则",
          "slug": "this的绑定规则"
        },
        {
          "level": 2,
          "title": "小结",
          "slug": "小结"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "你会写显示绑定方法吗？",
      "frontmatter": {
        "title": "你会写显示绑定方法吗？",
        "date": "2022-12-10T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "八股文"
        ],
        "categories": [
          "JavaScript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/JavaScript/xianshibangding.html",
      "relativePath": "handbook/JavaScript/xianshibangding.md",
      "key": "v-51d5f082",
      "path": "/handbook/JavaScript/xianshibangding.html",
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "快速理解JS中原型+原型链",
      "frontmatter": {
        "title": "快速理解JS中原型+原型链",
        "date": "2022-07-19T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "八股文"
        ],
        "categories": [
          "JavaScript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/JavaScript/yuanxing.html",
      "relativePath": "handbook/JavaScript/yuanxing.md",
      "key": "v-ff3b63e2",
      "path": "/handbook/JavaScript/yuanxing.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "原型",
          "slug": "原型"
        },
        {
          "level": 2,
          "title": "原型链",
          "slug": "原型链"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "小白必看——作用域与作用域链",
      "frontmatter": {
        "title": "小白必看——作用域与作用域链",
        "date": "2022-07-06T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "八股文"
        ],
        "categories": [
          "JavaScript"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/JavaScript/zuoyongyu.html",
      "relativePath": "handbook/JavaScript/zuoyongyu.md",
      "key": "v-390d00c2",
      "path": "/handbook/JavaScript/zuoyongyu.html",
      "headers": [
        {
          "level": 2,
          "title": "前言",
          "slug": "前言"
        },
        {
          "level": 2,
          "title": "作用域的概念",
          "slug": "作用域的概念"
        },
        {
          "level": 2,
          "title": "作用域的三大类型",
          "slug": "作用域的三大类型"
        },
        {
          "level": 2,
          "title": "词法作用域",
          "slug": "词法作用域"
        },
        {
          "level": 2,
          "title": "作用域链",
          "slug": "作用域链"
        },
        {
          "level": 2,
          "title": "作用域链概念",
          "slug": "作用域链概念"
        },
        {
          "level": 2,
          "title": "总结",
          "slug": "总结"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "最常见解决跨域的三种方式",
      "frontmatter": {
        "title": "最常见解决跨域的三种方式",
        "date": "2022-09-26T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "跨域"
        ],
        "categories": [
          "Node"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Node/kuayu.html",
      "relativePath": "handbook/Node/kuayu.md",
      "key": "v-07be16ff",
      "path": "/handbook/Node/kuayu.html",
      "headers": [
        {
          "level": 2,
          "title": "JSONP",
          "slug": "jsonp"
        },
        {
          "level": 2,
          "title": "Cors",
          "slug": "cors"
        },
        {
          "level": 2,
          "title": "Node代理",
          "slug": "node代理"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "在写vue的项目中为什么index不能做key使用？",
      "frontmatter": {
        "title": "在写vue的项目中为什么index不能做key使用？",
        "date": "2022-09-25T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "vue"
        ],
        "categories": [
          "Vue"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Vue/",
      "relativePath": "handbook/Vue/index.md",
      "key": "v-c701914c",
      "path": "/handbook/Vue/",
      "headers": [
        {
          "level": 3,
          "title": "key的作用",
          "slug": "key的作用"
        },
        {
          "level": 3,
          "title": "虚拟DOM树",
          "slug": "虚拟dom树"
        },
        {
          "level": 3,
          "title": "diff算法",
          "slug": "diff算法"
        },
        {
          "level": 2,
          "title": "index不能作为key的两种demo情况",
          "slug": "index不能作为key的两种demo情况"
        },
        {
          "level": 3,
          "title": "deom1",
          "slug": "deom1"
        },
        {
          "level": 3,
          "title": "demo2",
          "slug": "demo2"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "你知道Vue中router实现原理吗?",
      "frontmatter": {
        "title": "你知道Vue中router实现原理吗?",
        "date": "2022-10-10T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "router"
        ],
        "categories": [
          "Vue"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/Vue/router.html",
      "relativePath": "handbook/Vue/router.md",
      "key": "v-5b89e3f9",
      "path": "/handbook/Vue/router.html",
      "headers": [
        {
          "level": 2,
          "title": "vue官方版router",
          "slug": "vue官方版router"
        },
        {
          "level": 2,
          "title": "自己实现一个VueRouter",
          "slug": "自己实现一个vuerouter"
        },
        {
          "level": 3,
          "title": "VueRouter构造函数的实现",
          "slug": "vuerouter构造函数的实现"
        },
        {
          "level": 3,
          "title": "在Vue实例对象中混入Vue-Router",
          "slug": "在vue实例对象中混入vue-router"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "数组扁平化AND对象扁平化",
      "frontmatter": {
        "title": "数组扁平化AND对象扁平化",
        "date": "2022-12-09T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "扁平化"
        ],
        "categories": [
          "andition"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/andition/bianpinghua.html",
      "relativePath": "handbook/andition/bianpinghua.md",
      "key": "v-373c09df",
      "path": "/handbook/andition/bianpinghua.html",
      "headers": [
        {
          "level": 2,
          "title": "2.1 flat()方法",
          "slug": "_2-1-flat-方法"
        },
        {
          "level": 2,
          "title": "2.2 reduce() 方法+递归",
          "slug": "_2-2-reduce-方法-递归"
        },
        {
          "level": 2,
          "title": "2.3 不使用递归",
          "slug": "_2-3-不使用递归"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "面试题: 你会写发布订阅吗？",
      "frontmatter": {
        "title": "面试题: 你会写发布订阅吗？",
        "date": "2022-12-08T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "发布订阅"
        ],
        "categories": [
          "andition"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/andition/fabudingyue.html",
      "relativePath": "handbook/andition/fabudingyue.md",
      "key": "v-4d868802",
      "path": "/handbook/andition/fabudingyue.html",
      "headers": [
        {
          "level": 2,
          "title": "2.1 具体实现",
          "slug": "_2-1-具体实现"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "面试版简化Promise的实现",
      "frontmatter": {
        "title": "面试版简化Promise的实现",
        "date": "2022-08-29T00:00:00.000Z",
        "author": "穷小白",
        "tags": [
          "面试题"
        ],
        "categories": [
          "andition"
        ],
        "isShowComments": true,
        "subSidebar": "auto"
      },
      "regularPath": "/handbook/andition/promise.html",
      "relativePath": "handbook/andition/promise.md",
      "key": "v-59e905bf",
      "path": "/handbook/andition/promise.html",
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "关于作者",
      "frontmatter": {
        "title": "关于作者",
        "date": "2023-01-05T00:00:00.000Z",
        "sidebar": "auto"
      },
      "regularPath": "/views/About/author.html",
      "relativePath": "views/About/author.md",
      "key": "v-c4f33a16",
      "path": "/views/About/author.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "我的经历",
          "slug": "我的经历"
        },
        {
          "level": 2,
          "title": "目标",
          "slug": "目标"
        },
        {
          "level": 2,
          "title": "联系我",
          "slug": "联系我"
        }
      ],
      "excerpt": "",
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "这是我的简历",
      "frontmatter": {
        "title": "这是我的简历",
        "date": "2023-02-15T20:48:00.000Z",
        "sidebar": "auto",
        "sticky": 1
      },
      "regularPath": "/views/Resume/resume.html",
      "relativePath": "views/Resume/resume.md",
      "key": "v-9e23ecc2",
      "path": "/views/Resume/resume.html",
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "title": "快速上手",
      "frontmatter": {
        "title": "快速上手",
        "date": "2019-04-09T00:00:00.000Z"
      },
      "regularPath": "/views/other/guide.html",
      "relativePath": "views/other/guide.md",
      "key": "v-b08060b6",
      "path": "/views/other/guide.html",
      "headers": [
        {
          "level": 2,
          "title": "Use",
          "slug": "use"
        },
        {
          "level": 2,
          "title": "Play Together",
          "slug": "play-together"
        },
        {
          "level": 3,
          "title": "0.x",
          "slug": "_0-x"
        },
        {
          "level": 3,
          "title": "1.x",
          "slug": "_1-x"
        },
        {
          "level": 3,
          "title": "CLI",
          "slug": "cli"
        },
        {
          "level": 2,
          "title": "License",
          "slug": "license"
        }
      ],
      "lastUpdated": "2023/2/25 10:08:35",
      "lastUpdatedTimestamp": 1677290915000
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Object Tags"
      },
      "regularPath": "/tag/Object/",
      "key": "v-2393e274",
      "path": "/tag/Object/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "CSS Tags"
      },
      "regularPath": "/tag/CSS/",
      "key": "v-3259a754",
      "path": "/tag/CSS/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "Array Tags"
      },
      "regularPath": "/tag/Array/",
      "key": "v-7d137840",
      "path": "/tag/Array/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "ES6 Tags"
      },
      "regularPath": "/tag/ES6/",
      "key": "v-3257dcde",
      "path": "/tag/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "javaScript Tags"
      },
      "regularPath": "/tag/javaScript/",
      "key": "v-5f66a358",
      "path": "/tag/javaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "继承 Tags"
      },
      "regularPath": "/tag/%E7%BB%A7%E6%89%BF/",
      "key": "v-c784ecce",
      "path": "/tag/继承/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "深浅拷贝 Tags"
      },
      "regularPath": "/tag/%E6%B7%B1%E6%B5%85%E6%8B%B7%E8%B4%9D/",
      "key": "v-d74bd976",
      "path": "/tag/深浅拷贝/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "类型转换 Tags"
      },
      "regularPath": "/tag/%E7%B1%BB%E5%9E%8B%E8%BD%AC%E6%8D%A2/",
      "key": "v-0b8093b7",
      "path": "/tag/类型转换/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "八股文 Tags"
      },
      "regularPath": "/tag/%E5%85%AB%E8%82%A1%E6%96%87/",
      "key": "v-0df5b1b6",
      "path": "/tag/八股文/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "跨域 Tags"
      },
      "regularPath": "/tag/%E8%B7%A8%E5%9F%9F/",
      "key": "v-67cf2c0a",
      "path": "/tag/跨域/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue Tags"
      },
      "regularPath": "/tag/vue/",
      "key": "v-322a45da",
      "path": "/tag/vue/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "router Tags"
      },
      "regularPath": "/tag/router/",
      "key": "v-4081041c",
      "path": "/tag/router/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "扁平化 Tags"
      },
      "regularPath": "/tag/%E6%89%81%E5%B9%B3%E5%8C%96/",
      "key": "v-2892531a",
      "path": "/tag/扁平化/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "发布订阅 Tags"
      },
      "regularPath": "/tag/%E5%8F%91%E5%B8%83%E8%AE%A2%E9%98%85/",
      "key": "v-1d861698",
      "path": "/tag/发布订阅/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "面试题 Tags"
      },
      "regularPath": "/tag/%E9%9D%A2%E8%AF%95%E9%A2%98/",
      "key": "v-19493022",
      "path": "/tag/面试题/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Byte Categories"
      },
      "regularPath": "/categories/Byte/",
      "key": "v-60d1e5a9",
      "path": "/categories/Byte/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "ES6 Categories"
      },
      "regularPath": "/categories/ES6/",
      "key": "v-7eff4a05",
      "path": "/categories/ES6/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "JavaScript Categories"
      },
      "regularPath": "/categories/JavaScript/",
      "key": "v-081e6844",
      "path": "/categories/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Node Categories"
      },
      "regularPath": "/categories/Node/",
      "key": "v-617637ef",
      "path": "/categories/Node/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "Vue Categories"
      },
      "regularPath": "/categories/Vue/",
      "key": "v-7f0789a7",
      "path": "/categories/Vue/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "andition Categories"
      },
      "regularPath": "/categories/andition/",
      "key": "v-6eaeda0b",
      "path": "/categories/andition/"
    }
  ],
  "themeConfig": {
    "logo": "/headPortrait.jpg",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "目录"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      },
      "socialLinks": [
        {
          "link": "https://gitee.com/xiaopanpanya",
          "icon": "reco-mayun"
        },
        {
          "link": "https://github.com/xiaopanopan",
          "icon": "reco-github"
        },
        {
          "text": "稀土掘金",
          "link": "https://juejin.cn/user/4262162784847127/posts",
          "icon": "reco-juejin"
        },
        {
          "text": "Leetcode",
          "link": "https://leetcode.cn/u/silly-heyrovskys1p/",
          "icon": "reco-coding"
        }
      ]
    },
    "mode": "dark",
    "authorAvatar": "headPortrait.jpg",
    "type": "blog",
    "subSidebar": "auto",
    "lastUpdated": "上次更新",
    "nav": [
      {
        "text": "首页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      }
    ],
    "sidebar": "auto",
    "friendLink": [
      {
        "title": "vuepress-theme-reco",
        "desc": "A simple and beautiful vuepress Blog & Doc theme.",
        "logo": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      },
      {
        "title": "午后南杂",
        "desc": "Enjoy when you can, and endure when you must.",
        "email": "recoluan@qq.com",
        "link": "https://www.recoluan.com"
      }
    ],
    "markdown": {
      "lineNumbers": true
    },
    "valineConfig": {
      "appId": "OcpE2k26zVB0L3vtcpYl0uPK-gzGzoHsz",
      "appKey": "rp6d1uq9qMATS2zJnuviZ3ZS",
      "showComment": false,
      "placeholder": "发表评论~",
      "visitor": true,
      "avatarForce": true,
      "avatar": "monsterid"
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}