/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Object": {
      "key": "Object",
      "scope": "tags",
      "path": "/tag/Object/",
      "pageKeys": [
        "v-b5425aa6"
      ]
    },
    "Array": {
      "key": "Array",
      "scope": "tags",
      "path": "/tag/Array/",
      "pageKeys": [
        "v-29fe9c7f"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-78061042",
        "v-1fa58acf"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tag/ES6/",
      "pageKeys": [
        "v-7af95c37",
        "v-6a375eea",
        "v-0fdacb8b"
      ]
    },
    "继承": {
      "key": "继承",
      "scope": "tags",
      "path": "/tag/继承/",
      "pageKeys": [
        "v-3072887f",
        "v-6a1ada79"
      ]
    },
    "javaScript": {
      "key": "javaScript",
      "scope": "tags",
      "path": "/tag/javaScript/",
      "pageKeys": [
        "v-0801ecf5"
      ]
    },
    "深浅拷贝": {
      "key": "深浅拷贝",
      "scope": "tags",
      "path": "/tag/深浅拷贝/",
      "pageKeys": [
        "v-69d6624a"
      ]
    },
    "类型转换": {
      "key": "类型转换",
      "scope": "tags",
      "path": "/tag/类型转换/",
      "pageKeys": [
        "v-0cdc6c9f"
      ]
    },
    "八股文": {
      "key": "八股文",
      "scope": "tags",
      "path": "/tag/八股文/",
      "pageKeys": [
        "v-51d5f082",
        "v-ff3b63e2",
        "v-390d00c2"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-c701914c"
      ]
    },
    "跨域": {
      "key": "跨域",
      "scope": "tags",
      "path": "/tag/跨域/",
      "pageKeys": [
        "v-07be16ff"
      ]
    },
    "router": {
      "key": "router",
      "scope": "tags",
      "path": "/tag/router/",
      "pageKeys": [
        "v-5b89e3f9"
      ]
    },
    "扁平化": {
      "key": "扁平化",
      "scope": "tags",
      "path": "/tag/扁平化/",
      "pageKeys": [
        "v-373c09df"
      ]
    },
    "发布订阅": {
      "key": "发布订阅",
      "scope": "tags",
      "path": "/tag/发布订阅/",
      "pageKeys": [
        "v-4d868802"
      ]
    },
    "面试题": {
      "key": "面试题",
      "scope": "tags",
      "path": "/tag/面试题/",
      "pageKeys": [
        "v-59e905bf"
      ]
    }
  },
  "categories": {
    "Byte": {
      "key": "Byte",
      "scope": "categories",
      "path": "/categories/Byte/",
      "pageKeys": [
        "v-b5425aa6",
        "v-29fe9c7f",
        "v-78061042",
        "v-1fa58acf"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "categories",
      "path": "/categories/ES6/",
      "pageKeys": [
        "v-7af95c37",
        "v-6a375eea",
        "v-0fdacb8b"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-3072887f",
        "v-0801ecf5",
        "v-69d6624a",
        "v-0cdc6c9f",
        "v-6a1ada79",
        "v-51d5f082",
        "v-ff3b63e2",
        "v-390d00c2"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-c701914c",
        "v-5b89e3f9"
      ]
    },
    "Node": {
      "key": "Node",
      "scope": "categories",
      "path": "/categories/Node/",
      "pageKeys": [
        "v-07be16ff"
      ]
    },
    "andition": {
      "key": "andition",
      "scope": "categories",
      "path": "/categories/andition/",
      "pageKeys": [
        "v-373c09df",
        "v-4d868802",
        "v-59e905bf"
      ]
    }
  },
  "timeline": {}
}