/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "Array": {
      "key": "Array",
      "scope": "tags",
      "path": "/tag/Array/",
      "pageKeys": [
        "v-e5e0fe6e"
      ]
    },
    "Object": {
      "key": "Object",
      "scope": "tags",
      "path": "/tag/Object/",
      "pageKeys": [
        "v-f0706712"
      ]
    },
    "CSS": {
      "key": "CSS",
      "scope": "tags",
      "path": "/tag/CSS/",
      "pageKeys": [
        "v-9fe2b1ae",
        "v-aff5cace"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "tags",
      "path": "/tag/ES6/",
      "pageKeys": [
        "v-0358ec01",
        "v-3e3dd055",
        "v-a5656b56"
      ]
    },
    "javaScript": {
      "key": "javaScript",
      "scope": "tags",
      "path": "/tag/javaScript/",
      "pageKeys": [
        "v-df3d0682"
      ]
    },
    "继承": {
      "key": "继承",
      "scope": "tags",
      "path": "/tag/继承/",
      "pageKeys": [
        "v-0e5598c9",
        "v-1b0b2b7a"
      ]
    },
    "深浅拷贝": {
      "key": "深浅拷贝",
      "scope": "tags",
      "path": "/tag/深浅拷贝/",
      "pageKeys": [
        "v-13992cb6"
      ]
    },
    "跨域": {
      "key": "跨域",
      "scope": "tags",
      "path": "/tag/跨域/",
      "pageKeys": [
        "v-6acefb49"
      ]
    },
    "八股文": {
      "key": "八股文",
      "scope": "tags",
      "path": "/tag/八股文/",
      "pageKeys": [
        "v-71c273d9",
        "v-05314a2e",
        "v-7df24409"
      ]
    },
    "类型转换": {
      "key": "类型转换",
      "scope": "tags",
      "path": "/tag/类型转换/",
      "pageKeys": [
        "v-4ece73e9"
      ]
    },
    "vue": {
      "key": "vue",
      "scope": "tags",
      "path": "/tag/vue/",
      "pageKeys": [
        "v-b6468ab8"
      ]
    },
    "router": {
      "key": "router",
      "scope": "tags",
      "path": "/tag/router/",
      "pageKeys": [
        "v-82ca6f7a"
      ]
    },
    "发布订阅": {
      "key": "发布订阅",
      "scope": "tags",
      "path": "/tag/发布订阅/",
      "pageKeys": [
        "v-19aad16e"
      ]
    },
    "扁平化": {
      "key": "扁平化",
      "scope": "tags",
      "path": "/tag/扁平化/",
      "pageKeys": [
        "v-5129e529"
      ]
    },
    "面试题": {
      "key": "面试题",
      "scope": "tags",
      "path": "/tag/面试题/",
      "pageKeys": [
        "v-48a3cb09"
      ]
    }
  },
  "categories": {
    "Byte": {
      "key": "Byte",
      "scope": "categories",
      "path": "/categories/Byte/",
      "pageKeys": [
        "v-e5e0fe6e",
        "v-f0706712",
        "v-9fe2b1ae",
        "v-aff5cace"
      ]
    },
    "ES6": {
      "key": "ES6",
      "scope": "categories",
      "path": "/categories/ES6/",
      "pageKeys": [
        "v-0358ec01",
        "v-3e3dd055",
        "v-a5656b56"
      ]
    },
    "JavaScript": {
      "key": "JavaScript",
      "scope": "categories",
      "path": "/categories/JavaScript/",
      "pageKeys": [
        "v-df3d0682",
        "v-0e5598c9",
        "v-13992cb6",
        "v-1b0b2b7a",
        "v-71c273d9",
        "v-4ece73e9",
        "v-05314a2e",
        "v-7df24409"
      ]
    },
    "Node": {
      "key": "Node",
      "scope": "categories",
      "path": "/categories/Node/",
      "pageKeys": [
        "v-6acefb49"
      ]
    },
    "Vue": {
      "key": "Vue",
      "scope": "categories",
      "path": "/categories/Vue/",
      "pageKeys": [
        "v-b6468ab8",
        "v-82ca6f7a"
      ]
    },
    "andition": {
      "key": "andition",
      "scope": "categories",
      "path": "/categories/andition/",
      "pageKeys": [
        "v-19aad16e",
        "v-5129e529",
        "v-48a3cb09"
      ]
    }
  },
  "timeline": {}
}